### ISSUE TITLE
Convert to TypeScript?

### ISSUE THREAD

**Issue by tricinel** [center-key/fetch-json#27]
Hi @dpilafian! This is what I played around with. It's not a lot of changes in the original JS file, mainly some types here and there and a few tricks to make the TS compiler happy. The output looks to be the same, though we'll need to test it properly.

https://github.com/tricinel/fetch-json/blob/feature/types/src/index.ts

If you want to pull that down, you can run `npm run build` and it will generate:

- `dist/index.js` javascript without the types
- `dist/index.d.ts` the type declarations

You probably use the gulp command to build it properly, attach the version, etc. I haven't tested that yet.

**Comment by dpilafian** [comment]
If we make the jump to TypeScript for development, it probably makes sense to go all the way,  Otherwise, it could be confusing to have both `/src/index.ts` and `/fetch-json.js`.

What do you think about deleting `/fetch-json.js` and replacing it with `/fetch-json.ts`?  Of course, there would still be js in the `/dist` folder.

**Comment by tricinel** [comment]
Yes indeed! I did that just as a proof of concept, so I wanted to keep the original there for reference. I think you're completely right, we need to replace fetch-json with the ts and make sure the gulp tasks work as before.

I'll take care of that today and tomorrow and if everything checks out, I'll do PR.

Sound good?
