### ISSUE TITLE
Missing peerDependency `node-fetch`

### ISSUE THREAD

**Issue by bebbi** [center-key/fetch-json#31]
I think `package.json` needs `peerDependencies`?

```
  "peerDependencies": {
    "node-fetch": "~3.2"
  },
```

I've been bitten by this since upgrading yarn to `berry` which I think isolates dependencies in workspaces.

**Comment by bebbi** [comment]
Of course, I can't use `node-fetch` in my webpack/client project - I manually copied the source, removing the import statement for it to work for now.

**Comment by dpilafian** [comment]
This is an odd and frustrating situation caused by browsers having native fetch while **node** does not.

Some possible solutions:

1. Add an ESM version to the `dist` folder named something like `fetch-json.browser.js` or `fetch-json.native.js`.
2. Dynamically import `node-fetch` only if needed.  Something like: https://pretty-print-json.js.org/dynamic
3. Require **node** v18 with native `fetch` support.

It's not obvious how to best configure `exports` in **package.json**:
```json
   "exports": {
      ".": {
         "import": "./dist/fetch-json.js",
         "require": "./dist/fetch-json.umd.cjs"
      },
      "./": "./dist/"
   },
```

The `peerDependencies` route might cause issues for frontend projects.  

Every solution I can think of seems like a hack.  However, there is some good news.  **node** v18 has native `fetch` and it becomes the _active_ release just 20 days from now.

In the not too distant future (now?), the best solution may involve something like:
```json
"engines" : {
   "node" : ">=18.0.0"
}
```

Is there a good way out of this dilemma that I'm missing?
