### ISSUE TITLE
TypeScript Declaration

### ISSUE THREAD

**Issue by tobleron** [center-key/fetch-json#4]
Would highly appreciate typescript declaration file to be included with the package. I currently overcome this issue by adding a declaration in typings.d.ts file such as this:
declare module "fetch-json" { 
}

**Comment by dpilafian** [comment]
Sounds good.  I'm not sure on the best practices for ts declaration files, but if you put in a pull request I'll get it published out quickly.

**Comment by tricinel** [comment]
I took a look a this as well...My question would be...do you just want the TS types or rather convert everything to TypeScript?

**Comment by dpilafian** [comment]
Initially, probably just the TS types.  However, it makes sense to move development over to TS as long as the build process still produces a simple JS file that can be included via a CDN.

**Comment by tricinel** [comment]
Yep, makes sense. I've added the type declarations and partially rewrote (adapted) the js to ts, to check they work. More than happy to get the build system up and running properly so that it generates the JS file to be included via CDN. Nothing needs to change for the consumer really - just an improved developer experience.
